# -*- coding: utf-8 -*-
"""AI Major Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSO-R8hgcb7-_rkLkPc3q6OwDlcry_W3
"""

# ------------------------------------------------------------
# Expert System for Employee Performance Evaluation (Interactive)
# ------------------------------------------------------------
# Author: Sakshi Sachin More
# Description: Rule-based expert system that evaluates an employee’s
# performance based on entered employee ID.
# ------------------------------------------------------------

# ---- Knowledge Base ---- #
def evaluate_employee(emp):
    facts = {}
    score = 0

    # Rule-based scoring
    if emp.get("punctuality") == "excellent":
        score += 3
    elif emp.get("punctuality") == "good":
        score += 2
    elif emp.get("punctuality") == "average":
        score += 1

    if emp.get("task_completion_rate") >= 90:
        score += 3
    elif 75 <= emp.get("task_completion_rate") < 90:
        score += 2
    elif 60 <= emp.get("task_completion_rate") < 75:
        score += 1

    if emp.get("teamwork") == "excellent":
        score += 3
    elif emp.get("teamwork") == "good":
        score += 2
    elif emp.get("teamwork") == "average":
        score += 1

    if emp.get("innovation") == "yes":
        score += 2

    if emp.get("disciplinary_actions") > 0:
        score -= 2

    # Decision logic
    if score >= 10:
        facts["performance_level"] = "Excellent"
        facts["remarks"] = "Eligible for promotion and bonus."
    elif 7 <= score < 10:
        facts["performance_level"] = "Good"
        facts["remarks"] = "Maintain consistency. Consider skill upgrade."
    elif 4 <= score < 7:
        facts["performance_level"] = "Average"
        facts["remarks"] = "Needs improvement and training support."
    else:
        facts["performance_level"] = "Needs Improvement"
        facts["remarks"] = "Low performance. Schedule performance review."

    facts["total_score"] = score
    return facts


# ---- Employee Database ---- #
employees = [
    {
        "id": "E-101",
        "name": "Aarav Sharma",
        "punctuality": "excellent",
        "task_completion_rate": 95,
        "teamwork": "good",
        "innovation": "yes",
        "disciplinary_actions": 0
    },
    {
        "id": "E-102",
        "name": "Neha Patel",
        "punctuality": "good",
        "task_completion_rate": 80,
        "teamwork": "average",
        "innovation": "no",
        "disciplinary_actions": 0
    },
    {
        "id": "E-103",
        "name": "Ravi Kumar",
        "punctuality": "average",
        "task_completion_rate": 65,
        "teamwork": "good",
        "innovation": "no",
        "disciplinary_actions": 1
    },
    {
        "id": "E-104",
        "name": "Simran Kaur",
        "punctuality": "excellent",
        "task_completion_rate": 92,
        "teamwork": "excellent",
        "innovation": "yes",
        "disciplinary_actions": 0
    }
]


# ---- Inference Engine ---- #
def run_expert_system():
    print("\n=== EMPLOYEE PERFORMANCE EXPERT SYSTEM ===\n")
    print("👉 Available Employee ID Range: E-101 to E-104")
    print("👉 ID Format Example: E-101, E-102, E-103 ...\n")

    # Ask for employee ID
    emp_id = input("Enter Employee ID exactly as shown above: ").strip()

    # Search for employee record
    emp = next((e for e in employees if e["id"].lower() == emp_id.lower()), None)

    if emp:
        result = evaluate_employee(emp)
        print("\n--- Employee Evaluation Report ---")
        print(f"Employee ID   : {emp['id']}")
        print(f"Name          : {emp['name']}")
        print(f"Punctuality   : {emp['punctuality'].capitalize()}")
        print(f"Task Rate     : {emp['task_completion_rate']}%")
        print(f"Teamwork      : {emp['teamwork'].capitalize()}")
        print(f"Innovation    : {emp['innovation'].capitalize()}")
        print(f"Disciplinary Actions: {emp['disciplinary_actions']}")
        print("---------------------------------------------")
        print(f"Total Score   : {result['total_score']}")
        print(f"Performance   : {result['performance_level']}")
        print(f"Remarks       : {result['remarks']}")
        print("---------------------------------------------\n")
    else:
        print("\n⚠️ Employee ID not found. Please check and try again.\n")


# ---- Main ---- #
if __name__ == "__main__":
    run_expert_system()