# -*- coding: utf-8 -*-
"""AI MINI PROJECT3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOuhMTFhvWIbqO8I4ALSUU9BnCetES7V
"""



#3. “Tic-Tac-Toe AI Battle” (Alpha-Beta Pruning)
'''🎯 Idea:

User plays Tic-Tac-Toe against the computer.
AI uses Alpha-Beta pruning to find the best move. '''
import math

def print_board(board):
    for r in board:
        print(' | '.join(r))
        print('-'*5)

def winner(b):
    lines = [
        [b[0][0],b[0][1],b[0][2]],
        [b[1][0],b[1][1],b[1][2]],
        [b[2][0],b[2][1],b[2][2]],
        [b[0][0],b[1][0],b[2][0]],
        [b[0][1],b[1][1],b[2][1]],
        [b[0][2],b[1][2],b[2][2]],
        [b[0][0],b[1][1],b[2][2]],
        [b[0][2],b[1][1],b[2][0]],
    ]
    if ['X','X','X'] in lines: return 'X'
    if ['O','O','O'] in lines: return 'O'
    if all(b[r][c] != ' ' for r in range(3) for c in range(3)): return 'Tie'
    return None

def alphabeta(board, depth, alpha, beta, maximizing):
    w = winner(board)
    if w == 'X': return 1, None
    if w == 'O': return -1, None
    if w == 'Tie': return 0, None
    best_move = None
    if maximizing:
        val = -math.inf
        for r in range(3):
            for c in range(3):
                if board[r][c] == ' ':
                    board[r][c] = 'X'
                    score,_ = alphabeta(board, depth+1, alpha, beta, False)
                    board[r][c] = ' '
                    if score > val:
                        val, best_move = score, (r,c)
                    alpha = max(alpha, val)
                    if beta <= alpha: break
        return val, best_move
    else:
        val = math.inf
        for r in range(3):
            for c in range(3):
                if board[r][c] == ' ':
                    board[r][c] = 'O'
                    score,_ = alphabeta(board, depth+1, alpha, beta, True)
                    board[r][c] = ' '
                    if score < val:
                        val, best_move = score, (r,c)
                    beta = min(beta, val)
                    if beta <= alpha: break
        return val, best_move

if __name__ == "__main__":
    board = [[' ']*3 for _ in range(3)]
    print("Tic-Tac-Toe Game! You are O, Computer is X.")
    while True:
        print_board(board)
        if winner(board): break
        while True:
            try:
                move_input = input("Enter your move (row col 0-2): ").split()
                if len(move_input) == 2:
                    r, c = map(int, move_input)
                    if 0 <= r < 3 and 0 <= c < 3 and board[r][c] == ' ':
                        break
                    else:
                        print("Invalid move. Please enter row and column within range 0-2 for an empty cell.")
                else:
                    print("Invalid input format. Please enter row and column separated by a space.")
            except ValueError:
                print("Invalid input. Please enter numbers for row and column.")
        board[r][c] = 'O'
        if winner(board): break
        _, move = alphabeta(board, 0, -math.inf, math.inf, True)
        if move:
            board[move[0]][move[1]] = 'X'
    print_board(board)
    print("Result:", winner(board))